import type { Metadata, Viewport } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { Providers } from "@/provider/Providers";
import { Analytics } from "@vercel/analytics/react";
import Navigation from "@/components/Layout/Navigation";
import Footer from "@/components/Layout/Footer";
const font = Poppins({ subsets: ["latin"], weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'] });
export const viewport: Viewport = {
  themeColor: "#181818",
  colorScheme: "dark",
}

const metadataBase = new URL('http://localhost:3000/');

export const metadata: Metadata = {
  metadataBase,
  title: "AL - QURAN",
  description: "Generated by create next app",
  manifest: "/manifest.json",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="ltr" className="light">
      <body className={`${font.className} overflow-x-hidden min-h-screen`}>
        <Providers>
          <Navigation />
          {children}
          {/* <Footer /> */}
          <Analytics />
        </Providers>
      </body>
    </html>
  );
}
